/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __GRB1002_DEFS
#define __GRB1002_DEFS

#define GRB_NUM_INT_PARS 113
#define GRB_NUM_DBL_PARS 41
#define GRB_NUM_STR_PARS 25

#endif //__GRB1002_DEFS
