/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __GRB1200_DEFS
#define __GRB1200_DEFS

#define GRB_NUM_INT_PARS 120
#define GRB_NUM_DBL_PARS 42
#define GRB_NUM_STR_PARS 28

#endif //__GRB1200_DEFS
