/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __HiGHS1100_DEFS
#define __HiGHS1100_DEFS

#define HiGHS_NUM_INT_PARS 87
#define HiGHS_NUM_DBL_PARS 31
#define HiGHS_NUM_STR_PARS 11

#endif //__HiGHS1100_DEFS
