/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __HiGHS171_DEFS
#define __HiGHS171_DEFS

#define HiGHS_NUM_INT_PARS 78
#define HiGHS_NUM_DBL_PARS 29
#define HiGHS_NUM_STR_PARS 10

#endif //__HiGHS171_DEFS
