/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __HiGHS170_DEFS
#define __HiGHS170_DEFS

#define HiGHS_NUM_INT_PARS 76
#define HiGHS_NUM_DBL_PARS 29
#define HiGHS_NUM_STR_PARS 10

#endif //__HiGHS170_DEFS
