/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __HiGHS1110_DEFS
#define __HiGHS1110_DEFS

#define HiGHS_NUM_INT_PARS 92
#define HiGHS_NUM_DBL_PARS 34
#define HiGHS_NUM_STR_PARS 14

#endif //__HiGHS1110_DEFS
