/* FILE GENERATED AUTOMATICALLY, DO NOT EDIT */

#ifndef __SCIP921_DEFS
#define __SCIP921_DEFS

#define SCIP_NUM_INT_PARS 194
#define SCIP_NUM_DBL_PARS 70
#define SCIP_NUM_STR_PARS 18

#endif //__SCIP921_DEFS
